name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: backend/SolarWatch
      run: dotnet restore

    - name: Build
      working-directory: backend/SolarWatch
      run: dotnet build --no-restore -c Release

    - name: Test
      working-directory: backend/SolarWatch
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      working-directory: backend/SolarWatch
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: SolarWatch
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: publish
